blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/VectorInstitute/aieng-template-uv/discussions
    about: Ask questions or discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/VectorInstitute/aieng-template-uv#readme
    about: Check the documentation for setup and usage guides
