# Image Generation Configuration (OpenAI)
dalle_config:
  model: "dall-e-3" # "dall-e-2", "dall-e-3", "gpt-image-1"
  quality: "standard" # "standard" or "hd"
  style: "vivid" # "vivid", "natural"
  img_size: "1024x1024" # Options are "1024x1024", "1024x1792", "1792x1024" for DALL-E 3 and extra options for DALL-E 2 ("256x256", "512x512")

# Text Generation Configuration (OpenAI)
gpt_config:
  model: "gpt-4o" # "gpt-4", "gpt-4o", "gpt-4o-mini", "gpt-3.5-turbo"
  batch_size: 1
  max_tokens: 2048
  temperature: 0.7 # Controls randomness in output (0.0 = deterministic, 1.0 = more random)

# Image Generation Configuration (Gemini)
gemini_config:
  model: "imagen-4.0-generate-001" # "imagen-4.0-generate-001", "imagen-4.0-ultra-generate-001", "imagen-4.0-fast-generate-001", "imagen-3.0-generate-002"
  numberOfImages: 1 # Number of images to generate per prompt (1-4)
  sampleImageSize: "1K" # Image size for Gemini (options: "1K", "2K")
  aspectRatio: "1:1" # Aspect ratio for Gemini (options: "1:1", "3:4", "4:3", "9:16", and "16:9")
  personGeneration: "ALLOW_ALL" # Options: "ALLOW_ALL", "ALLOW_ADULT", "DONT_ALLOW"
