# Image Generation Configuration (OpenAI)
dalle:
  model: "dall-e-3" # "dall-e-2", "dall-e-3", "gpt-image-1"
  quality: "standard" # "standard" or "hd"
  style: "vivid" # "vivid", "natural"
  img_size: "1024x1024" # Options are "1024x1024", "1024x1792", "1792x1024" for DALL-E 3 and extra options for DALL-E 2 ("256x256", "512x512")

# Text Generation Configuration (OpenAI)
gpt:
  model: "gpt-4o" # "gpt-4", "gpt-4o", "gpt-4o-mini", "gpt-3.5-turbo"
  batch_size: 1
  max_tokens: 2048
  temperature: 0.7 # Controls randomness in output (0.0 = deterministic, 1.0 = more random)

# Image Generation Configuration (Gemini)
gemini:
  model: "imagen-4.0-generate-001" # "imagen-4.0-generate-001", "imagen-4.0-ultra-generate-001", "imagen-4.0-fast-generate-001", "imagen-3.0-generate-002"
  numberOfImages: 1 # Number of images to generate per prompt (1-4)
  sampleImageSize: "1K" # Image size for Gemini (options: "1K", "2K")
  aspectRatio: "1:1" # Aspect ratio for Gemini (options: "1:1", "3:4", "4:3", "9:16", and "16:9")
  personGeneration: "ALLOW_ALL" # Options: "ALLOW_ALL", "ALLOW_ADULT", "DONT_ALLOW"

# Video Generation Configuration (Veo models)
veo:
  model: "veo-3.0-generate-preview" # "veo-3.0-generate-preview", "veo-3.0-fast-generate-preview", "veo-2.0-generate-001",
  aspectRatio: "16:9" # Aspect ratio for Veo-3 is only "16:9". Veo-2 supports "16:9" and "9:16"
  personGeneration: "ALLOW_ALL" # For Veo-3: "ALLOW_ALL" only. For Veo-2: "ALLOW_ALL", "ALLOW_ADULT", "DONT_ALLOW"
  numberOfVideos: 1 # For Veo-3: 1 only. For Veo-2: 1 or 2 videos per prompt.
  # Note about Veo models: Both Veo-3 and Veo-2 generate 720p videos at 24 fps. Video length for Veo-3 = 8 seconds and for Veo-2 = 5-8 seconds. Veo-3 generates 1 video per request and Veo-2 can generate up to 2 videos per request. Veo-3 has audio inbuilt, Veo-2 does not have audio. Veo-3 has requests Per Day (RPD) as 10 and Veo-2 has RPD as 50. Veo-3 and Veo-2 has requests Per Minute (RPM) as 2. Veo-3 = 0.40$ per second, Veo-3 fast is 0.15 and Veo-2 is 0.35$ per second of video generated.
